huacnlee/rails-settings-cached

README.md

`Settings.get_all` was introduced in `0.4.0` version, before that, `Settings.all` performed the same role.

Update README about Settings.get_all difference

---

lib/rails-settings/cached_settings.rb

Hi huacnlee,
I found that `save_default` cannot work if there is the same name of a method defined.
For example, `Settng.save_default('name', 'foo') # It would fail`, because `Setting.name` would output `"Setting"`.
I think that there may be several kinds of solutions for it.
The patch I submitted is just to fix the problem with the fewest code change.
But I think that it may be a better idea to raise an exception when a user tries to assign a key which name is a conflict with built-in methods.
I would be appreciated hearing your opinion.
Thanks a lot. :smile:

Fix method name cannot be setting's key

---

README.md
lib/rails-settings/cached_settings.rb
spec/rails-settings-cached/cached_setting_spec.rb

So that settings can be arbitrarily scoped based on some
context (e.g. current tenant).

Allow setting dynamic cache prefix

---

rails-settings-cached.gemspec

Enabling the use for an generally [unsupported platform without any security support](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/) would send wrong signals and maintenance for it shouldn't be relevant at all.
This PR IMHO should make #74 obsolete.

declare supported ruby versions as requirement

---

lib/rails-settings/settings.rb

Hi. To integrate with gem [administrate](https://github.com/thoughtbot/administrate), it is necessary to `Setting.new.value` return `nil`, otherwise we get this error:
```
TypeError - no implicit conversion of nil into String:
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:318:in `parse'
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:245:in `load'
rails-settings-cached (0.5.2) lib/rails-settings/settings.rb:19:in `value'
```

Administrate integration

---

lib/rails-settings/cached_settings.rb
spec/rails-settings-cached/cached_setting_spec.rb

If setting a cache value is called within a TX and then the value is
accessed, then the old value is retrieved from the cache.
The fix is to clear the cached value for the var name immediately after
calling save!. Note, it is still appropriate to clear cache values upon
commit due to race conditions.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/huacnlee/rails-settings-cached/86)

Update the cached value for the key when value set

---

CHANGELOG.md
Gemfile.lock
README.md
lib/rails-settings/cached_settings.rb
lib/rails-settings/version.rb

Fixes an issue where RailsSettings::CachedSettings uses the deprecated class RailsSettings::Settings
Fixes: #95

Fix CachedSettings inheritance

---

lib/rails-settings/base.rb
spec/rails-settings-cached/setting_spec.rb

If the value was set to false, either the default is returned or if
there is no default, then nil would be returned.
I have added a test that would previously fail that now passes.

Fix bug preventing a value of false from being returned

---

lib/rails-settings/settings.rb
spec/rails-settings-cached/setting_spec.rb

This addresses an issue with `#get_all` and default values. If a default value exists for key `x` and a value for `x` also exists in the database, the current implementation of `#get_all` will override the database value with the default value.
I also noticed that the current test suite is order dependent. Try running the test suite with `rspec --order rand` and things start t o break in all kinds of interesting ways.

Ensure defaults not overwrite persisted settings

---

lib/generators/settings/templates/model.rb

DEPRECATION WARNING: RailsSettings::CachedSettings is deprecated and it will removed in 0.7.0. Please use RailsSettings::Base instead.

Fix deprecated syntax in the model generator

---

lib/rails-settings/settings.rb
spec/rails-settings-cached/setting_spec.rb

Subj. Select defaults, not fetch.
Otherwise starting_with selection can be wrong.
Also added another `defaults` fix with specs.

Fix defaults merge when get_all.

---

.travis.yml
lib/rails-settings/default.rb
rails-settings-cached.gemspec

Performance should be slightly better than #fetch (https://github.com/JuanitoFatas/fast-ruby#hashdig-vs-hash-vs-hashfetch-code)
And i propose to drop support of older ruby version that does not support `Hash#dig` (< 2.3.0)

Use Hash#dig to fetch nested defaults

---

lib/rails-settings/default.rb

Installations that do not have a 'config/app.yml' file will fail to start. This just adds a simple test for the file before attempting to load it.

Only load default config file if it exists

---

README.md

Following semver, it was apparent that 2.x would have breaking changes, but my bundle was auto-updated to 2.x without the version spec in the gem file.
Might be good to specify a version requirement in the readme example, as many gems do:
```ruby
gem "rails-settings-cached", "~> 2.0"
```
Then once a future breaking version is released (e.g. 3.x.x or 4.x.x) it won't break existing codebases without an intentional upgrade to the new major version.

Add version spec to Gemfile in README

---

lib/generators/settings/install_generator.rb
lib/rails-settings/version.rb

The generator was explicitly checking if the Rails major version was 5 so the migration version wasn't being set in a Rails 6 project. Assuming using a migration version will continue being the standard this PR changes that check to Rails >= 5.

Fix migration version for Rails 6

---

README.md

Hey @huacnlee is it possible that this line is nowhere defined? Or am I missing something?
I searched `get_settings` in this repository and could not find a definition in this code base and only some probably out-dated issues mentioning it.

docs: remove obsolete `get_settings`

---

Gemfile.lock
README.md
lib/rails-settings/base.rb
test/test_helper.rb
test/validation_test.rb

https://github.com/huacnlee/rails-settings-cached/pull/201
```rb
irb> Setting.app_name = ""
ActiveRecord::RecordInvalid: (Validation failed: App name can't be blank)
irb> Setting.app_name = "Rails Settings"
"Rails Settings"
irb> Setting.default_locale = "zh-TW"
ActiveRecord::RecordInvalid: (Validation failed: Default locale is not included in [zh-CN, en, jp])
irb> Setting.default_locale = "en"
"en"
```
This changes can backward compatible, because the old version not have `validates` option.

Validate on assignment

---

lib/rails-settings/base.rb
test/base_test.rb

Fix #212 not can use `f.select` with Setting instance method.
Change to limit use `var`, `value` as Setting key.

Allows call key in Setting instance to support use keys in ActionView helpers

---

lib/rails-settings-cached.rb
lib/rails-settings/base.rb
lib/rails-settings/fields/array.rb
lib/rails-settings/fields/base.rb
lib/rails-settings/fields/big_decimal.rb
lib/rails-settings/fields/boolean.rb
lib/rails-settings/fields/float.rb
lib/rails-settings/fields/hash.rb
lib/rails-settings/fields/integer.rb
lib/rails-settings/fields/string.rb
test/base_test.rb
test/dummy/app/models/rails_settings/fields/custom.rb
test/dummy/app/models/setting.rb

Hi!
Currently, the library supports only a limited number of types - `array, hash, big_decimal, integer, float, string, boolean`.
I have a need to save custom types into a DB, so I decided to try to add the functionality that will allow me to do that. During implementation, I also tried to refactor a little bit of other code in order to make it more readable.
So here is what I've done so far:
- Added ability to define custom types with their own serializers by splitting fields by types into separate classes (https://github.com/MrKirat/rails-settings-cached/tree/kirat/add-ability-to-add-custom-types/lib/rails-settings/fields) and adding dynamic lookup (https://github.com/MrKirat/rails-settings-cached/blob/kirat/add-ability-to-add-custom-types/lib/rails-settings/fields/base.rb#L62-L71)
- …

Add ability to define custom data types

---

lib/rails-settings-cached.rb
lib/rails-settings/base.rb
lib/rails-settings/configuration.rb
test/base_test.rb
test/configuration_test.rb
test/dummy/lib/active_support/cache/dummy_store.rb

Resolves https://github.com/huacnlee/rails-settings-cached/issues/234
Configuration example:
```ruby
RailsSettings.configure do
self.storage = ActiveSupport::Cache::RedisCacheStore.new(url: "redis://localhost:6379")
end
```

Implement configurable storage backend

---

lib/rails-settings-cached.rb
lib/rails-settings/base.rb
lib/rails-settings/railtie.rb

Referencing `ActiveRecord::Base` as soon as the gem is required cause Active Record being loaded earlier than it should and some Rails configurations not to take effect.
Ref: https://github.com/rails/rails/issues/49827
Ref: https://github.com/mastodon/mastodon/pull/28609
cc @ClearlyClaire @mjankowski

Delay loading of Active Record
